name = "Plain"
license = "MIT"
source_repo = "https://github.com/aubergene/hugo-plain"
description = "A minimal theme, for learning and customization."

[author]
    name = "Julian Burgess"
    email = "aubergene@gmail.com"
    url = "https://aubergene.com"

